spring.application.name=crm-api
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/CRM
spring.datasource.username=admin
spring.datasource.password=manthann05

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true